import Head from 'next/head'
import { useRouter } from 'next/router'
import useUser from '@/hooks/useUser'
import { List, ListItem } from '@mui/material'
import { User } from '@/hooks/useUsers'

export default function Index(usersData: User) {
  const router = useRouter()
  const { id } = router.query
  const [user, loading, error] = useUser(id! + '')

  if (loading) {
    return <div>Loading...</div>
  }

  if (error) {
    console.log(id)
    return <div>Error: {error.message}</div>
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <List>
          <ListItem key={user?.id}>Name: {user?.name}</ListItem>
          <ListItem key={user?.id}>Username: {user?.username}</ListItem>
          <ListItem key={user?.id}>Email: {user?.email}</ListItem>
          <ListItem key={user?.id}>Street: {user?.address.street}</ListItem>
          <ListItem key={user?.id}>City: {user?.address.city}</ListItem>
          <ListItem key={user?.id}>Zipcode: {user?.address.zipcode}</ListItem>
          <ListItem key={user?.id}>Phone number: {user?.phone}</ListItem>
        </List>
      </main>
    </>
  )
}
